-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 11:03:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_facebook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_facebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_facebook` DEFAULT CHARACTER SET utf8 ;
USE `db_facebook` ;

-- -----------------------------------------------------
-- Table `db_facebook`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facebook`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facebook`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facebook`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `commentaire` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facebook`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facebook`.`media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `image` LONGBLOB NULL,
  PRIMARY KEY (`idMedia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facebook`.`media_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facebook`.`media_post` (
  `media_idMedia` INT NOT NULL,
  `post_idPost` INT NOT NULL,
  PRIMARY KEY (`media_idMedia`, `post_idPost`),
  INDEX `fk_media_has_post_post1_idx` (`post_idPost` ASC) VISIBLE,
  INDEX `fk_media_has_post_media_idx` (`media_idMedia` ASC) VISIBLE,
  CONSTRAINT `fk_media_has_post_media`
    FOREIGN KEY (`media_idMedia`)
    REFERENCES `db_facebook`.`media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_post_post1`
    FOREIGN KEY (`post_idPost`)
    REFERENCES `db_facebook`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
